[window]
decorations = "none"
opacity = 0.8
startup_mode = "Windowed"
dynamic_title = true
title = "Alacritty"
dimensions = { columns = 90, lines = 30 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 12.0

[scrolling]
history = 10000
multiplier = 3

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 500

[colors.primary]
background = "#212122"
foreground = "#f8f8f2"

[colors.normal]
black   = "#21222c"
red     = "#ff5555"
green   = "#50fa7b"
yellow  = "#f1fa8c"
blue    = "#bd93f9"
magenta = "#ff79c6"
cyan    = "#8be9fd"
white   = "#f8f8f2"

[colors.bright]
black   = "#6272a4"
red     = "#ff6e6e"
green   = "#69ff94"
yellow  = "#ffffa5"
blue    = "#ffacfb"
magenta = "#ff92df"
cyan    = "#a4ffff"
white   = "#ffffff"
